In [2]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print(array1)

[1 2 3]


In [5]:
type(array1)

numpy.ndarray

In [7]:
list1 = [1,2,3]
type(list1)
array1 = np.array(list1)
type(array1)

numpy.ndarray

In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)
print(array_int, array_int.dtype)

array_float = np.array([1.2, 2.3, 3.4])
array_int1 = array_float.astype('int32')
print(array_float, array_float.dtype)
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1.2 2.3 3.4] float64
[1 2 3] int32


In [4]:
array2 = np.arange(18)
zero_array = np.zeros((3,2), dtype = 'int32')
one_array = np.ones((4,2))
print(zero_array, zero_array.dtype)
print(one_array, one_array.dtype)

[[0 0]
 [0 0]
 [0 0]] int32
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [ ]:
array1

In [1]:
import requests, json

def current_location():
    here_req = requests.get("http://www.geoplugin.net/json.gp")

    if (here_req.status_code != 200):
        print("현재좌표를 불러올 수 없음")
    else:
        location = json.loads(here_req.text)
        crd = {"lat": str(location["geoplugin_latitude"]), "lng": str(location["geoplugin_longitude"])}

    return crd

crd = current_location()
print(crd)

{'lat': '37.5662', 'lng': '126.8309'}


In [5]:
from geopy.geocoders import Nominatim

def geocoding_reverse(lat_lng_str): 
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse(lat_lng_str)

    return address

address = geocoding_reverse('37.5662, 126.8309')
print(address)

마곡지구도시개발지구, 가양1동, 강서구, 서울, 07594, 대한민국


In [13]:
import os
import sys
import urllib.request
client_id = "ms5CGPZn7da7grSHvD5H"
client_secret = "kCdzeO49AQ"
url = "https://openapi.naver.com/v1/datalab/search";
body = "{\"startDate\":\"2017-01-01\",\"endDate\":\"2017-04-30\",\"timeUnit\":\"month\",\"keywordGroups\":[{\"groupName\":\"한글\",\"keywords\":[\"한글\",\"korean\"]},{\"groupName\":\"영어\",\"keywords\":[\"영어\",\"english\"]}],\"device\":\"pc\",\"ages\":[\"1\",\"2\"],\"gender\":\"f\"}";

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
request.add_header("Content-Type","application/json")
response = urllib.request.urlopen(request, data=body.encode("utf-8"))
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

{"startDate":"2017-01-01","endDate":"2017-04-30","timeUnit":"month","results":[{"title":"한글","keywords":["한글","korean"],"data":[{"period":"2017-01-01","ratio":47.00101},{"period":"2017-02-01","ratio":53.23619},{"period":"2017-03-01","ratio":100},{"period":"2017-04-01","ratio":85.327}]},{"title":"영어","keywords":["영어","english"],"data":[{"period":"2017-01-01","ratio":40.0881},{"period":"2017-02-01","ratio":36.69942},{"period":"2017-03-01","ratio":52.11792},{"period":"2017-04-01","ratio":44.4595}]}]}


In [12]:
import pandas as pd
import urllib.request
import json


client_id = "ms5CGPZn7da7grSHvD5H"
client_secret = "kCdzeO49AQ"

url = "https://openapi.naver.com/v1/datalab/search"
body = "{\
         \"startDate\":\"2022-10-01\",\
         \"endDate\":\"2022-10-04\",\
         \"timeUnit\":\"date\",\
         \"keywordGroups\":[{\"groupName\":\"아이패드\",\"keywords\":[\"아이패드\"]},\
                             {\"groupName\":\"갤럭시 탭\",\"keywords\":[\"갤럭시 탭\"]}\
                            ],\
         \"device\":\"pc\",\
         \"ages\":[\"4\"],\
         \"gender\":\"m\"\
         }";

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
request.add_header("Content-Type","application/json")

response = urllib.request.urlopen(request, data=body.encode("utf-8"))

rescode = response.getcode()

if(rescode==200):
    response_body = response.read()
    response_data = response_body.decode('utf-8')
else:
    print("Error Code:" + rescode)

result = json.loads(response_data)

print(result)

date = [a['period'] for a in result['results'][0]['data']]
ratio_data1 = [a['ratio'] for a in result['results'][0]['data']]
ratio_data2 = [a['ratio'] for a in result['results'][1]['data']]


pd.DataFrame({'날짜':date,
        '아이패드':ratio_data1,
        '갤럭시 탭':ratio_data2})

{'startDate': '2022-10-01', 'endDate': '2022-10-04', 'timeUnit': 'date', 'results': [{'title': '아이패드', 'keywords': ['아이패드'], 'data': [{'period': '2022-10-01', 'ratio': 57.54189}, {'period': '2022-10-02', 'ratio': 54.7486}, {'period': '2022-10-03', 'ratio': 57.54189}, {'period': '2022-10-04', 'ratio': 100}]}, {'title': '갤럭시 탭', 'keywords': ['갤럭시 탭'], 'data': [{'period': '2022-10-01', 'ratio': 20.67039}, {'period': '2022-10-02', 'ratio': 25.13966}, {'period': '2022-10-03', 'ratio': 25.13966}, {'period': '2022-10-04', 'ratio': 39.10614}]}]}


날짜       아이패드     갤럭시 탭
0  2022-10-01   57.54189  20.67039
1  2022-10-02   54.74860  25.13966
2  2022-10-03   57.54189  25.13966
3  2022-10-04  100.00000  39.10614

In [2]:
import openai

openai.api_key = "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"

messages = []
while True:
    content = input("입력: ")
    messages.append({"role":"user", "content":content})

    completion = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
        messages = messages
    )

    response = completion['choices'][0]['message']['content'].strip()
    print("chatGPT: "+response)

    messages.append({"role": "assistant", "content": response})

입력: 다음 글을 읽고 요약해줘.  본인의 성장과정을 간략히 기술하되 현재의 자신에게 가장 큰 영향을 끼친 사건, 인물 등을 포함하여 기술하시기 바랍니다. (※작품속 가상인물도 가능) 보기 답변 “야구에서 인생을 보다”  저는 야구를 참 좋아합니다. 야구를 좋아하고, 야구에 빠져들게 된 계기는 2008 베이징 올림픽, 2009 WBC 두 대회에서 국가대표팀의 우수한 성적이었습니다. 당시 대한민국 대표팀은 도저히 이길 수 없을 것 같고 강해 보이는 상대에게 끝까지 물고 늘어지며 열세를 극복하는 모습들을 보여주었습니다. 어린 기억 속에 자리 잡은 그 모습은 저에게 끝까지 포기하지 않고 노력하게 되는 원동력으로 자리 잡았습니다. 야구에서는 “끝날 때까지 끝난 게 아니다”라는 말이 있습니다. 1973년 7월, 뉴욕 메츠 감독이었던 요기 베라가 리그에서 최하위였을 때 한 말입니다. 제가 정말 좋아하는 말입니다. 선두와 9.5게임 차였던 메츠는 기적적으로 리그 1위로 순위를 마감하였습니다. 야구는 확률의 스포츠입니다. 그러나 야구에 0과 1은 없습니다. 어떤 일이 어떤 상황에서 벌어질지 알 수 없습니다. 때론 매우 큰 실수가 동료들의 도움으로 무마되기도 하고, 나의 작은 실수가 역전의 발판이 되기도 합니다.  저는 인생 또한 그러하다고 생각합니다. 어렸을 적, 아버지의 사업 실패로 인해 남들보다 부족한 삶을 살아왔습니다. 아버지는 막노동, 택시운전 등 가정을 위해 안 해보신 일이 없으셨고, 어머니께서도 여러 아르바이트를 전전하시며 일을 하셨어야 했습니다. 그러나 부모님께서는 이런 환경 속에서도 저와 동생 두 아들들에게는 부족하지만 최우선으로 최선을 다해 보살펴 주시어, 단 한번의 학자금 대출 없이 무사히 대학 교육까지 지원해 주셨습니다. 사업의 큰 실패를 겪었던 저희 아버지도 지금은 식당을 운영하시며 안정적인 수입을 유지하고 계십니다. 가족들을 위해 포기하지 않고 끝까지 노력하신 결과라고 생각합니다.  어렵고 포기하고 싶은 순간에서도 저는 저희 아버지를 생각하며, 아직 

KeyboardInterrupt: Interrupted by user